# Generated by Django 5.1.3 on 2024-11-29 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_pedido', models.PositiveIntegerField()),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='fk_pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.pedido'),
            preserve_default=False,
        ),
    ]
