# Generated by Django 5.1.3 on 2024-11-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_pedido_producto_fk_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero_de_pedido',
            new_name='numero_pedido',
        ),
    ]
