# Generated by Django 5.1.3 on 2024-11-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_numero_de_pedido_pedido_numero_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fk_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
            preserve_default=False,
        ),
    ]
