# Generated by Django 5.1.3 on 2024-11-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_producto_fk_pedido_pedido_fk_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
    ]
