# Generated by Django 5.1.3 on 2024-12-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_pedido_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_producto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.PositiveIntegerField(verbose_name='Número pedido'),
        ),
    ]
