# Generated by Django 5.1.3 on 2024-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_pedido_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fk_pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fk_pedido',
            field=models.ManyToManyField(to='inventario.producto'),
        ),
    ]
