# Generated by Django 5.1.3 on 2024-12-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_pedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='m2m_producto',
            field=models.ManyToManyField(related_name='productos', to='inventario.producto', verbose_name='Productos'),
        ),
    ]
