# Generated by Django 5.1.3 on 2024-12-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_alter_pedido_m2m_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='m2m_producto',
        ),
    ]
