# Generated by Django 5.1.3 on 2024-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_detallespedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(through='inventario.DetallesPedido', to='inventario.producto', verbose_name='Productos'),
        ),
    ]
